stages:
  - deploy

deploy-job:
  stage: deploy
  environment: production
  script:
    - echo "Deploying application..."
    - ssh -tt chris@thor.docker '
        cd docker_files/APIs/JobHunt_API && 
        git restore . &&
        git pull &&
        npm install &&
        docker image rm jobhunt
        docker build -t jobhunt . &&
        docker compose down &&
        docker compose up -d'
    - echo "Application successfully deployed."