
services:
  jobhuntapi:
    build:
      context: .
    image: jobhuntapi:latest
    networks:
      - MyDockerNetwork
    ports:
      - "5000"
    restart: "unless-stopped"
#    volumes:
#      - /etc/letsencrypt:/etc/letsencrypt

  nginx_jobhuntapi:
    image: nginx:latest
    container_name: nginx_jobhuntapi
    networks:
      MyDockerNetwork:
        ipv4_address: 192.168.3.103
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
#      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - jobhuntapi
    ports:
      - "80:80"
#      - "443:443"
    restart: "unless-stopped"

networks:
  MyDockerNetwork:
    external: true

  
