version: "3.8"

services:
  jobhuntapi:
    build:
      context: .
    image: jobhuntapi:latest
    networks:
      - My_2ndDocker_Network
    ports:
      - "5000"
#    volumes:
#      - /etc/letsencrypt:/etc/letsencrypt

  nginx_jobhuntapi:
    image: nginx:latest
    container_name: nginx_jobhuntapi
    networks:
      My_2ndDocker_Network:
        ipv4_address: 192.168.3.103
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
#      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - jobhuntapi
    ports:
      - "80:80"
#      - "443:443"

networks:
  My_2ndDocker_Network:
    external: true

  
